version: '2.4'

services:
  # Web application
  app:
    build: .
    restart: always
    ports:
      - "5000:5000"
    volumes:
      - type: bind
        source: ./uploads
        target: /app/uploads
      - type: bind
        source: ./data
        target: /app/data
    environment:
      - DATABASE_URL=postgresql://journal_user:journal_password@db:5432/journal
      - DB_USER=journal_user
      - DB_PASSWORD=journal_password
      - DB_NAME=journal
      - DB_HOST=db
      - DEMO_MODE=True
      - SESSION_SECRET=default-secret-key-change-me
    depends_on:
      - db

  # PostgreSQL database
  db:
    image: postgres:14-alpine
    restart: always
    environment:
      - POSTGRES_USER=journal_user
      - POSTGRES_PASSWORD=journal_password
      - POSTGRES_DB=journal
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  db-data: